## Regresión lineal
### El paquete scikit-learn para regresión lineal y la selección de rasgos

In [4]:
import numpy as np
import pandas as pd
import os
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [2]:
mainpath="/Volumes/Developer/Study/Udemy/Machine Learning/python-ml-course/datasets"
filename="ads/Advertising.csv"
fullpath= os.path.join(mainpath, filename)

In [5]:
data = pd.read_csv(fullpath)

Primero determinamos cuales columnas de datos son relevante para el modelo

In [8]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [10]:
X = data[feature_cols]
Y = data["Sales"]

In [14]:
# Se usa el SVR para crear el modelo
estimator = SVR(kernel="linear")
#determino con RFE, se crea un modelo lineal con dos variables predictivas en un solo paso (step)
selector= RFE(estimator,n_features_to_select=2, step=1)
#Luego crea el modelo con las X y Y que he creado
selector = selector.fit(X,Y)

In [15]:
#permite seleccionar las columnas
selector.support_

array([ True,  True, False])

In [16]:
selector.ranking_

array([1, 1, 2])

Utilizamos LinearRegression para crear el modelo lineal

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
x_pred = X[["TV", "Radio"]]

In [24]:
lm = LinearRegression()
lm.fit(x_pred, Y)

LinearRegression()

In [25]:
#El intercepto
lm.intercept_

2.9210999124051362

In [26]:
#Son los coeficientes de cada dato
lm.coef_

array([0.04575482, 0.18799423])

In [23]:
lm.score(x_pred, y)

0.8971942610828956